// <auto-generated />
namespace Service.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Atualiza_banco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Atualiza_banco));
        
        string IMigrationMetadata.Id
        {
            get { return "202001191932424_Atualiza_banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
